package com.rl.ecps.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-06-27T22:53:21.155+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "freemarketService", 
                  wsdlLocation = "http://localhost:8080/ecps-portal/services/publishItem?wsdl",
                  targetNamespace = "http://service.ws.ecps.rl.com/") 
public class FreemarketService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.ecps.rl.com/", "freemarketService");
    public final static QName FreemarketPort = new QName("http://service.ws.ecps.rl.com/", "freemarketPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ecps-portal/services/publishItem?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FreemarketService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ecps-portal/services/publishItem?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FreemarketService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FreemarketService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FreemarketService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FreemarketService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FreemarketService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FreemarketService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns FreemarketPortType
     */
    @WebEndpoint(name = "freemarketPort")
    public FreemarketPortType getFreemarketPort() {
        return super.getPort(FreemarketPort, FreemarketPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FreemarketPortType
     */
    @WebEndpoint(name = "freemarketPort")
    public FreemarketPortType getFreemarketPort(WebServiceFeature... features) {
        return super.getPort(FreemarketPort, FreemarketPortType.class, features);
    }

}
