package com.rl.ecps.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-06-27T22:53:21.077+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.ws.ecps.rl.com/", name = "freemarketPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface FreemarketPortType {

    @WebMethod
    @RequestWrapper(localName = "publishItem", targetNamespace = "http://service.ws.ecps.rl.com/", className = "com.rl.ecps.stub.PublishItem")
    @ResponseWrapper(localName = "publishItemResponse", targetNamespace = "http://service.ws.ecps.rl.com/", className = "com.rl.ecps.stub.PublishItemResponse")
    @WebResult(name = "returnWord", targetNamespace = "")
    public java.lang.String publishItem(
        @WebParam(name = "itemId", targetNamespace = "")
        java.lang.Long itemId,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    ) throws IOException_Exception, TemplateException_Exception;
}
