
package com.rl.ecps.stub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-06-27T22:53:21.061+08:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "TemplateException", targetNamespace = "http://service.ws.ecps.rl.com/")
public class TemplateException_Exception extends Exception {
    
    private com.rl.ecps.stub.TemplateException templateException;

    public TemplateException_Exception() {
        super();
    }
    
    public TemplateException_Exception(String message) {
        super(message);
    }
    
    public TemplateException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public TemplateException_Exception(String message, com.rl.ecps.stub.TemplateException templateException) {
        super(message);
        this.templateException = templateException;
    }

    public TemplateException_Exception(String message, com.rl.ecps.stub.TemplateException templateException, Throwable cause) {
        super(message, cause);
        this.templateException = templateException;
    }

    public com.rl.ecps.stub.TemplateException getFaultInfo() {
        return this.templateException;
    }
}
